@BASE_URL = http://127.0.0.1:8080

# @name CreateUser
POST {{BASE_URL}}/users HTTP/1.1
Content-Type: application/json

{
    "username": "aqqlcq",
    "full_name": "aqqlcqw",
    "email": "aqqlcq@gmail.com",
    "password": "secret"
}
###
# @name LoginUser
POST {{BASE_URL}}/users/login HTTP/1.1
Content-Type: application/json

{
    "username": "aqqlcq",
    "password": "secret"
}
###

@ACCESS_TOKEN = {{LoginUser.response.body.access_token}}




# @name CreateAccount
POST {{BASE_URL}}/accounts HTTP/1.1
Authorization: bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "owner": "aqqlcq",
    "currency": "TWD"
}
###
# @name GetListAccount
GET  {{BASE_URL}}/accounts?page_id=1&page_size=5 HTTP/1.1
Authorization: bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    
}
###

# @name GetAccount
GET  {{BASE_URL}}/accounts/29 HTTP/1.1
Authorization: bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    
}
###



# @name CreateTransfers
POST  {{BASE_URL}}/transfers HTTP/1.1
Authorization: bearer {{ACCESS_TOKEN}}
Content-Type: application/json

{
    "from_account_id":29,
    "to_account_id":2,
    "amount": 10,
    "currency":"TWD"
}
###



