@baseUrl = http://127.0.0.1:8080

# @name CreateAccount
POST {{baseUrl}}/accounts HTTP/1.1
Content-Type: application/json

{
    "owner": "Tiger",
    "currency": "USD"
}
###

# @name GetAccount
GET  {{baseUrl}}/accounts/1 HTTP/1.1
Content-Type: application/json

{
    
}
###

# @name GetAccount
GET  {{baseUrl}}/accounts/-1 HTTP/1.1
Content-Type: application/json

{
    
}
###

# @name GetListAccount
GET  {{baseUrl}}/accounts?page_id=0&page_size=5 HTTP/1.1
Content-Type: application/json

{
    
}
###

# @name createTransfers
POST  {{baseUrl}}/transfers HTTP/1.1
Content-Type: application/json

{
    "from_account_id":3,
    "to_account_id":2,
    "amount": 10,
    "currency":"USD"
}
###