-- MySQL Script generated by MySQL Workbench
-- Wed Feb 22 23:02:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema transferDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema transferDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `transferDB` DEFAULT CHARACTER SET utf8 ;
USE `transferDB` ;

-- -----------------------------------------------------
-- Table `transferDB`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accounts` (
  `id` BIGINT(20) UNSIGNED NOT NULL,
  `owner` VARCHAR(255) NOT NULL,
  `balance` BIGINT(20) UNSIGNED NOT NULL,
  `currency` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX `owner` (`owner` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transferDB`.`entries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entries` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `amount` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `account_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_id_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_id`
    FOREIGN KEY (`account_id`)
    REFERENCES `transferDB`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `transferDB`.`transfers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `transfers` (
  `id` BIGINT(20) NOT NULL,
  `from_account_id` BIGINT(20) UNSIGNED NOT NULL,
  `to_account_id` BIGINT(20) UNSIGNED NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `fk_from_account_id_idx` (`from_account_id` ASC) VISIBLE,
  INDEX `fk_to_account_id_idx` (`to_account_id` ASC) VISIBLE,
  CONSTRAINT `fk_from_account_id`
    FOREIGN KEY (`from_account_id`)
    REFERENCES `transferDB`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_to_account_id`
    FOREIGN KEY (`to_account_id`)
    REFERENCES `transferDB`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
