// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
)

type Account struct {
	ID        int64
	Owner     string
	Balance   int64
	Currency  string
	CreatedAt sql.NullTime
}

type Entry struct {
	ID        int64
	Amount    int64
	CreatedAt sql.NullTime
	AccountID int64
}

type Transfer struct {
	ID            int64
	FromAccountID int64
	ToAccountID   int64
	CreatedAt     sql.NullTime
}
