name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: mysql service on docker
      run: make mysql

    - name: wait db and db migratrion
      run: chmod +x ./wait-for.sh & sh ./wait-for.sh localhost:3306 & make migrateup

    - name: Test
      run: make test